on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.6

      - name: Run tests with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-jar
          path: lib/build/libs/*.jar
