on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.6

      - name: Run tests with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
